analyzer:
  errors:
    body_might_complete_normally_catch_error: ignore
    unnecessary_null_comparison: ignore
    use_key_in_widget_constructors: ignore
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    
