// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcSaqeg07Umm2lTFjrmL_XWghVHDTyFLo',
    appId: '1:871781911758:web:97fd7c8c0426d8b28dd49f',
    messagingSenderId: '871781911758',
    projectId: 'polikan',
    authDomain: 'polikan.firebaseapp.com',
    storageBucket: 'polikan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR47kfD4OQFe5oo_r-5enm6Uf0UObaT40',
    appId: '1:871781911758:android:d18b361539a2e5058dd49f',
    messagingSenderId: '871781911758',
    projectId: 'polikan',
    storageBucket: 'polikan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrhwKiDDiPxbkUHkGedQa5yNjUnXaLxUM',
    appId: '1:871781911758:ios:34f2f6c357343ca88dd49f',
    messagingSenderId: '871781911758',
    projectId: 'polikan',
    storageBucket: 'polikan.appspot.com',
    iosBundleId: 'com.smkmq.polikan',
  );
}
